"""Initial tables

Revision ID: adf207b1266b
Revises: 
Create Date: 2025-09-01 18:32:49.225222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adf207b1266b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_ingestion_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('rows_processed', sa.Integer(), nullable=False),
    sa.Column('rows_successful', sa.Integer(), nullable=False),
    sa.Column('rows_failed', sa.Integer(), nullable=False),
    sa.Column('processing_time_ms', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('insurance_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('policy_number', sa.String(length=50), nullable=False),
    sa.Column('insured_name', sa.String(length=200), nullable=False),
    sa.Column('sum_insured', sa.Float(), nullable=False),
    sa.Column('premium', sa.Float(), nullable=False),
    sa.Column('own_retention_ppn', sa.Float(), nullable=False),
    sa.Column('own_retention_sum_insured', sa.Float(), nullable=False),
    sa.Column('own_retention_premium', sa.Float(), nullable=False),
    sa.Column('treaty_ppn', sa.Float(), nullable=False),
    sa.Column('treaty_sum_insured', sa.Float(), nullable=False),
    sa.Column('treaty_premium', sa.Float(), nullable=False),
    sa.Column('insurance_period_start_date', sa.Date(), nullable=False),
    sa.Column('insurance_period_end_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_policies_insurance_period_end_date'), 'insurance_policies', ['insurance_period_end_date'], unique=False)
    op.create_index(op.f('ix_insurance_policies_insurance_period_start_date'), 'insurance_policies', ['insurance_period_start_date'], unique=False)
    op.create_index(op.f('ix_insurance_policies_insured_name'), 'insurance_policies', ['insured_name'], unique=False)
    op.create_index(op.f('ix_insurance_policies_policy_number'), 'insurance_policies', ['policy_number'], unique=True)
    op.create_index('ix_policy_amounts', 'insurance_policies', ['sum_insured', 'premium'], unique=False)
    op.create_index('ix_policy_period', 'insurance_policies', ['insurance_period_start_date', 'insurance_period_end_date'], unique=False)
    op.create_index('ix_treaty_info', 'insurance_policies', ['treaty_ppn', 'treaty_sum_insured', 'treaty_premium'], unique=False)
    op.create_table('query_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('query_type', sa.String(length=50), nullable=True),
    sa.Column('processing_time_ms', sa.Float(), nullable=False),
    sa.Column('langgraph_steps', sa.Integer(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('query_logs')
    op.drop_index('ix_treaty_info', table_name='insurance_policies')
    op.drop_index('ix_policy_period', table_name='insurance_policies')
    op.drop_index('ix_policy_amounts', table_name='insurance_policies')
    op.drop_index(op.f('ix_insurance_policies_policy_number'), table_name='insurance_policies')
    op.drop_index(op.f('ix_insurance_policies_insured_name'), table_name='insurance_policies')
    op.drop_index(op.f('ix_insurance_policies_insurance_period_start_date'), table_name='insurance_policies')
    op.drop_index(op.f('ix_insurance_policies_insurance_period_end_date'), table_name='insurance_policies')
    op.drop_table('insurance_policies')
    op.drop_table('data_ingestion_logs')
    # ### end Alembic commands ###
